### REGISTER
POST http://localhost:3000/auth/register
Content-Type: application/json

{
   "email": "mail@example.com",
   "fullName": "John Doe",
   "password": "Test@123"
}

### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
   "email": "mail@example.com",
   "password": "Test@1233"
}

### VERIFY EMAIL
GET http://localhost:3000/auth/verify/_3PwEp

