@baseUrl = http://localhost:3000/api/auth

### REGISTER
POST {{baseUrl}}/signup
Content-Type: application/json

{
   "email": "mail@example.com",
   "fullName": "John Doe",
   "password": "Test@123"
}

### LOGIN
POST {{baseUrl}}/signin
Content-Type: application/json

# {
#    "email": "trung@example.com",
#    "password": "Trung@341"
# }

### VERIFY EMAIL
GET {{baseUrl}}/verify/xAomGD52

