### GET A USER BY ID
GET http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNzQwMzcxNjY5LCJleHAiOjE3NDAzNzE3Mjl9.KWcOjJn2mQHDUY3CqZxmkLQ_C_MOLBWpZbOXMNHBkY0

### UPDATE USER
PUT http://localhost:3000/users/3
Content-Type: application/json

{
   "fullName": "Duy Trung",
   "bio": "Lorem ipsum",
   "avatar": "https://example.com/avatar.jpg",
   "personal": {
      "phone": "0930000000",
      "dateOfBirth": "2025-01-01"
   },
   "professional": {
      "company": "A1B2C3",
      "position": "Employee"
   }
}