@baseUrl = http://localhost:3000/api/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiZW1haWwiOiJ0cnVuZ0BleGFtcGxlLmNvbSIsImZ1bGxuYW1lIjoiRHV5IFRydW5nIiwiaWF0IjoxNzQwODMwODMwLCJleHAiOjE3NDA4MzA4OTB9.BQthowclyON3mJG7bbeMrLE2oyfSQPyK8-rqD96F2As

### GET A USER BY ID
GET {{baseUrl}}/1
Authorization: Bearer {{token}}

### UPDATE USER
PUT {{baseUrl}}/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "fullName": "Duy Trung 123",
   "bio": "Lorem ipsum",
   "avatar": "https://example.com/avatar.jpg",
   "personal": {
      "phone": "0930000000",
      "dateOfBirth": "2025-01-01"
   },
   "professional": {
      "company": "A1B2C3",
      "position": "Employee"
   }
}

### 
POST {{baseUrl}}/block
Authorization: Bearer {{token}}